<?
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="R";
$PERM["lichnyy-kabinet-prodavtsa"]["*"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="R";
$PERM["lichnyy-kabinet-pokupatelya"]["*"]="D";
$PERM["bitrix"]["8"]="R";
$PERM["services"]["8"]="W";
$PERM["services"]["5"]="W";
$PERM["search"]["8"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["8"]="W";
$PERM["products"]["5"]="W";
$PERM["news"]["8"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["8"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["8"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>